### PR TITLE
Authentication Fixes

### LINKED ISSUE #48: Authentication Fixes
As mentioned 
- LoginPage and RegisterPage should redirect to ProfilePage if user is authenticated.
- Use [Context](https://reactjs.org/docs/context.html) to store the currently logged in user and the setUser function (with `React.useState` on App.js) -- here's a quick [video tutorial](https://www.youtube.com/watch?v=lhMKvyLRWo0) that may help
- Refactor to single top-level `user` check on App.js with AuthenticatedApp and UnauthenticatedApp components, details [here](https://kentcdodds.com/blog/authentication-in-react-applications). Use the `/coop` GET request to set the user object after logging in!
- Finally, refactor the ProfilePage to use the user object from context rather than making the `/coop` GET request.

It will probably be most helpful to look at an example, so check out the [react-auth-context](https://github.com/rrrliu/express-lesson/tree/react-auth-context) branch here and compare it to the [react-auth](https://github.com/rrrliu/express-lesson/tree/react-auth) branch.

### PR DESCRIPTION
**Pull request by Claire-Thib**
Fixes #48

## Summary of Changes

Feel free to use sentences or a bulleted list.

- Created context.js file
- Created Authenticated and Unauthenticated functions
- Removed redirect and replaced with change of user to null
- Fixed location bug

## Testing

Explain how you tested these changes (unit tests, manual UI testing, etc.) or N/A if testing is not necessary (and explain why).

N/A

### CODE REVIEW

File: client/src/pages/FiltersPage/FiltersPage.js [hunk 1]
```diff
@@ -285,9 +285,9 @@ export default function FiltersPage() {
     showStarredOnly ? setShowStarredOnly(false) : setShowStarredOnly(true);
   }
 
-  if (redirect) {
-    return <Redirect to="/login" />;
-  }
+  // if (redirect) {
+  //   return <Redirect to="/login" />;
+  // }
```
Comment (rrrliu) [inline client/src/pages/FiltersPage/FiltersPage.js]: rm

File: client/src/pages/ProfilePage/ProfilePage.js [hunk 2]
```diff
@@ -285,6 +280,9 @@ export default function ProfilePage() {
     };
     await axios.put('/api/coop', data);
     setProfileVariables(data);
+    console.log('SET VARS putdata ');
+    console.log({ latLng });
```
Comment (rrrliu) [inline client/src/pages/ProfilePage/ProfilePage.js]: rm

File: db/cofed.sql [hunk 3]
```diff
@@ -51,6 +51,18 @@ GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO root;
...
+    ('ericseggplants@gmail.com', '123456', 'Erics Eggplants', '555-678-3456', 'Berkeley, CA', 57.8715, -128.273, 'https://loveradish.co.uk/', 'Ensuring no harm comes to any eggplants we raise', 'We are a family owned farm that have raised chickens for years. However, in an attempt to go green we have switched our focus to raising plants now.', 'https://drive.google.com/file/d/1d-cjNcHPo3hx-Jbuw7OmH_hhIdfTHzs0/view?usp=sharing', 'https://instagram.com', 'https://facebook.com'),
+    ('yummychicken@gmail.com', '123456123456', 'Zaids Chickens', '209-368-2456', 'Tracy, CA', 37.7396, -121.4260, 'https://www.mypetchicken.com/', 'Best local chicken', 'Fresh poultry', 'https://drive.google.com/file/d/1hOavbQnu73JlXIssPO90GYbtBmcF8bQ7/view?usp=sharing', 'https://instagram.com', 'https://facebook.com');
```
Comment (rrrliu) [inline db/cofed.sql]: remove these inserts

File: db/cofed.sql [hunk 4]
```diff
@@ -59,3 +71,20 @@ VALUES
...
+    (3, 1),
+    (1, 1),
+    (4, 1),
+    (5, 3), 
+    (3, 4),
+    (5, 1),
+    (8, 1),
+    (8, 4),
+    (7, 3),
+    (7, 2);
```
Comment (rrrliu) [inline db/cofed.sql]: also remove these

**Review by rrrliu — CHANGES_REQUESTED** [review]

**Review by rrrliu — DISMISSED** [review]

**Review by rrrliu — APPROVED** [review]
